Neos:
  Neos:
    fusion:
      autoInclude:
        Networkteam.Neos.Mockup: true
    userInterface:
      translation:
        autoInclude:
          Networkteam.Neos.Mockup:
            - 'NodeTypes/*'

Networkteam:
  Neos:
    Mockup:
      active: true
      title: 'Mockup'