Neos:
  Neos:
    fusion:
      autoInclude:
        Networkteam.Neos.Mockup: true
    userInterface:
      translation:
        autoInclude:
          Networkteam.Neos.Mockup:
            - 'NodeTypes/*'



Neos:
  Neos:
    fusion:
      autoInclude:
        Neos.NodeTypes: true
    userInterface:
      translation:
        autoInclude:
          Neos.NodeTypes:
            - 'NodeTypes/*'

Networkteam:
  Neos:
    Mockup:
      active: true
